[package]
name = "wakapi-anyide"
version = "0.6.6"
edition = "2021"

authors = ["Sarah C", "Asher E"]

[lib]
name = "wakapi_anyide"
crate-type = ["cdylib"]

[dependencies]
notify = "7.0.0"

[dependencies.pyo3]
version = "0.22.5"
features = ["abi3-py312", "extension-module"]
